#ifndef DUKPT_CLI_CONFIG_H
#define DUKPT_CLI_CONFIG_H

#define DUKPT_CLIENT_NOT_OS
#define DUKPT_NOT_IO
/* #define DUKPT_CLIENT_PKAUTH_STRING */
/* #define DUKPT_CLIENT_TR31_STD */
/* #define DUKPT_CLIENT_ZERO_PADDING */

#endif
